name: Hello World
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
jobs:
  say-hello-inline:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello from an inline bash script in a GitHub Action Workflow!"

  say-hello-action:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b # v1.2.3
        # - uses: actions/hello-world-javascript-action@v1 # This would work, but it would be less stable and less secure:
        with:
          who-to-greet: "from an action in the GitHub Action marketplace! ðŸ‘‹"
