name: Container Actions
on:
  workflow_dispatch:

jobs:
  shell-dockerfile:
    runs-on: ubuntu-latest
    name: Shell Container Action (dynamic Dockerfile build)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Run container action
        uses: ./06-authoring-actions/container-actions/shell-container-action
        id: hello
        with:
          who-to-greet: "from a container github action ðŸ‘‹"
      - name: Get the output greeting
        run: echo "The greeting was ${{ steps.hello.outputs.greeting }}"

  shell-public-container-image:
    runs-on: ubuntu-latest
    name: Shell Container Action (public container image)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run container action
        uses: ./06-authoring-actions/container-actions/shell-container-action-prebuilt
        id: hello
        with:
          who-to-greet: "from a container github action ðŸ‘‹"
      - name: Get the output greeting
        run: echo "The greeting was ${{ steps.hello.outputs.greeting }}"

  python-dockerfile:
    runs-on: ubuntu-latest
    name: Shell Container Action (dynamic Dockerfile build)
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run container action
        uses: ./06-authoring-actions/container-actions/python-container-action
        id: hello
        with:
          who-to-greet: "from a container github action ðŸ‘‹"
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.greeting }}"
